######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 8 12:51:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += back.h dialog.h
SOURCES += back.cc main.cc 

QT += network


